// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDGdp6s0e2_HMo8xgncCYkr3q-8C7P6zA',
    appId: '1:645005702198:web:0a7e74133f1148096b5497',
    messagingSenderId: '645005702198',
    projectId: 'kervia-app',
    authDomain: 'kervia-app.firebaseapp.com',
    storageBucket: 'kervia-app.firebasestorage.app',
    measurementId: 'G-Y9XEEH42J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyhCsJQFaBIW3mgrFStTSzLrUQQkYG-_w',
    appId: '1:645005702198:android:38918b02ca08bb276b5497',
    messagingSenderId: '645005702198',
    projectId: 'kervia-app',
    storageBucket: 'kervia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGWGidqqXZzzgeQp7GZffTcxRghZKMwVg',
    appId: '1:645005702198:ios:bc4520607e99fe556b5497',
    messagingSenderId: '645005702198',
    projectId: 'kervia-app',
    storageBucket: 'kervia-app.firebasestorage.app',
    iosClientId: '645005702198-ut4ovup0fovqqlarffuko5bsdr93banb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kervia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDGdp6s0e2_HMo8xgncCYkr3q-8C7P6zA',
    appId: '1:645005702198:web:3a289de73fcc6caa6b5497',
    messagingSenderId: '645005702198',
    projectId: 'kervia-app',
    authDomain: 'kervia-app.firebaseapp.com',
    storageBucket: 'kervia-app.firebasestorage.app',
    measurementId: 'G-DK0BYKV7HP',
  );
}
